spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/frm?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  activiti:
    check-process-definitions: false